import { LOCALE } from "./i18n.js";

export const FALLBACK_CONFIG = {
  homer: {
    url: "",
  },
  theme: {},
  search: {
    defaultEngineId: "yandex",
    engines: [
      {
        id: "yandex",
        title: LOCALE === "ru" ? "Яндекс" : "Yandex",
        template: "https://yandex.ru/search/?text={q}",
      },
    ],
  },
  quickLinks: [],
  visits: {
    frequentHistoryPool: 5000,
    frequentMinVisits: 3,
  },
  weather: {
    topWidgetPlacement: "center",
  },
  githubTrending: {
    excludedTerms: [],
    syncIntervalMinutes: 60,
  },
  news: {
    defaultSourcesVersion: 4,
    sources: [
      {
        id: "hacker-news",
        title: "Hacker News",
        type: "hackerNews",
        url: "https://hacker-news.firebaseio.com/v0/topstories.json",
        enabled: true,
        syncIntervalMinutes: 45,
        maxItems: 12,
      },
      {
        id: "reddit-dev",
        title: "Reddit",
        type: "reddit",
        url: "https://www.reddit.com/r/programming+webdev+technology/hot.json?limit=16",
        enabled: true,
        syncIntervalMinutes: 45,
        maxItems: 12,
      },
      {
        id: "habr",
        title: "Habr",
        type: "rss",
        url: "https://habr.com/ru/rss/best/daily/?fl=ru",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 12,
      },
      {
        id: "vc",
        title: "vc.ru",
        type: "rss",
        url: "https://vc.ru/rss/all",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 12,
      },
      {
        id: "ai-trends",
        title: "AI Trends",
        type: "rss",
        url: "https://shir-man.com/api/rss?sort=trending",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 12,
      },
      {
        id: "ai-trends-day",
        title: "AI Trends Day",
        type: "rss",
        url: "https://shir-man.com/api/rss?sort=day",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 12,
      },
      {
        id: "ai-trends-week",
        title: "AI Trends Week",
        type: "rss",
        url: "https://shir-man.com/api/rss?sort=week",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 12,
      },
      {
        id: "ai-trends-month",
        title: "AI Trends Month",
        type: "rss",
        url: "https://shir-man.com/api/rss?sort=month",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 12,
      },
      {
        id: "ai-trends-hacker-news",
        title: "AI Trends HN",
        type: "shirMan",
        url: "https://shir-man.com/api/feed?sort=trending",
        sourceKey: "hackerNews",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 12,
      },
      {
        id: "ai-trends-midjourney",
        title: "AI Trends Midjourney",
        type: "shirMan",
        url: "https://shir-man.com/api/feed?sort=trending",
        sourceKey: "midjourney",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 36,
      },
      {
        id: "ai-trends-github",
        title: "AI Trends GitHub",
        type: "shirMan",
        url: "https://shir-man.com/api/feed?sort=trending",
        sourceKey: "github",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 12,
      },
      {
        id: "ai-trends-hype-replicate",
        title: "AI Trends Hype Replicate",
        type: "shirMan",
        url: "https://shir-man.com/api/feed?sort=trending",
        sourceKey: "hypeReplicate",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 12,
      },
      {
        id: "ai-trends-lesswrong",
        title: "AI Trends LessWrong",
        type: "shirMan",
        url: "https://shir-man.com/api/feed?sort=day",
        sourceKey: "lessWrong",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 12,
      },
      {
        id: "ai-trends-lobsters",
        title: "AI Trends Lobsters",
        type: "shirMan",
        url: "https://shir-man.com/api/feed?sort=trending",
        sourceKey: "lobsters",
        enabled: true,
        syncIntervalMinutes: 60,
        maxItems: 12,
      },
    ],
  },
  services: [],
};
